export const GUIDE_SOURCE = 'ICAR / State Agricultural University general guidance';
export const GUIDE_URL = 'https://icar.gov.in/';
export const CROP_GUIDES = [
  { crop: 'tomato', title_en: 'Tomato - Complete Crop Guide', title_hi: 'टमाटर - संपूर्ण मार्गदर्शिका', title_mr: 'टोमॅटो - संपूर्ण मार्गदर्शक',
    overview_en: 'General guidance. Short-duration vegetable for fresh market. Confirm variety and dates locally with KVK.',
    overview_hi: 'सामान्य मार्गदर्शन। ताजे बाजार हेतु अल्पकालिक सब्जी। किस्म व तिथि KVK से पुष्ट करें।',
    overview_mr: 'सर्वसाधारण मार्गदर्शन. ताज्या बाजारासाठी अल्पकालीन भाजीपाला. वाण व तारीख KVK कडून खात्री करा.',
    conditions_en: 'General guidance. Warm season, well-drained loam, pH 6-7. Avoid waterlogging.',
    conditions_hi: 'सामान्य मार्गदर्शन। गर्म मौसम, दोमट निकास मिट्टी, पीएच 6-7। जलभराव से बचें।',
    conditions_mr: 'सर्वसाधारण मार्गदर्शन. उबदार हंगाम, मध्यम निचऱ्याची जमीन, सामू 6-7. पाणी साचू देऊ नका.',
    sowing_en: 'General guidance. Transplant 3-4 week seedlings. Spacing and seed rate per local advisory.',
    sowing_hi: 'सामान्य मार्गदर्शन। 3-4 सप्ताह पौध रोपें। अंतर व बीज दर स्थानीय सलाह अनुसार।',
    sowing_mr: 'सर्वसाधारण मार्गदर्शन. 3-4 आठवड्यांची रोपे लावा. अंतर व बियाणे स्थानिक सल्ल्यानुसार.',
    stages_en: 'Nursery, transplanting, vegetative, flowering, fruiting, harvest.',
    stages_hi: 'नर्सरी, रोपाई, वृद्धि, फूल, फल, कटाई।',
    stages_mr: 'रोपवाटिका, लागवड, वाढ, फुले, फळे, काढणी.',
    irrigation_en: 'General guidance. Regular light irrigation; drip is efficient. Avoid wetting foliage.',
    irrigation_hi: 'सामान्य मार्गदर्शन। नियमित हल्की सिंचाई; ड्रिप लाभकारी। पत्ते भिगोने से बचें।',
    irrigation_mr: 'सर्वसाधारण मार्गदर्शन. नियमित हलके पाणी; ठिबक फायदेशीर. पाने भिजवू नका.',
    diseases_en: 'Common: Early Blight, Late Blight, Bacterial Spot. See disease details in app.',
    diseases_hi: 'सामान्य: अगेती/पछेती झुलसा, जीवाणु धब्बा। विवरण ऐप में देखें।',
    diseases_mr: 'सामान्य: अर्ली/लेट ब्लाइट, बॅक्टेरियल स्पॉट. माहिती अ‍ॅपमध्ये पहा.',
    prevention_en: 'General prevention: clean seedlings, rotation, sanitation. No chemical dose here - follow approved label.',
    prevention_hi: 'सामान्य रोकथाम: स्वच्छ पौध, फसल चक्र, सफाई। कोई मात्रा यहां नहीं - लेबल मानें।',
    prevention_mr: 'सर्वसाधारण प्रतिबंध: स्वच्छ रोपे, फेरपालट, स्वच्छता. मात्रा नाही - लेबल पाळा.',
    harvest_en: 'General guidance. Pick mature-green to red per market. Handle gently.',
    harvest_hi: 'सामान्य मार्गदर्शन। बाजार अनुसार तोड़ें। सावधानी से संभालें।',
    harvest_mr: 'सर्वसाधारण मार्गदर्शन. बाजारानुसार तोडा. काळजीने हाताळा.',
    source: 'ICAR / State Agricultural University general guidance', source_url: 'https://icar.gov.in/' }
];
CROP_GUIDES.push({ crop: 'potato', title_en: 'Potato - Complete Crop Guide', title_hi: 'आलू - संपूर्ण मार्गदर्शिका', title_mr: 'बटाटा - संपूर्ण मार्गदर्शक',
  overview_en: 'General guidance. Rabi tuber crop. Use certified seed tubers. Confirm window locally.',
  overview_hi: 'सामान्य मार्गदर्शन। रबी कंद फसल। प्रमाणित बीज कंद प्रयोग करें।',
  overview_mr: 'सर्वसाधारण मार्गदर्शन. रब्बी कंद पीक. प्रमाणित बेणे वापरा.',
  conditions_en: 'General guidance. Cool season, loose drained soil. Avoid frost and waterlogging.',
  conditions_hi: 'सामान्य मार्गदर्शन। ठंडा मौसम, भुरभुरी निकास मिट्टी। पाला व जलभराव से बचें।',
  conditions_mr: 'सर्वसाधारण मार्गदर्शन. थंड हंगाम, भुसभुशीत निचऱ्याची जमीन. हिम व पाणी साचणे टाळा.',
  sowing_en: 'General guidance. Plant sprouted tubers at recommended depth and spacing per local advisory.',
  sowing_hi: 'सामान्य मार्गदर्शन। अंकुरित कंद अनुशंसित गहराई व अंतर पर लगाएं।',
  sowing_mr: 'सर्वसाधारण मार्गदर्शन. मोड आलेले कंद शिफारस खोली व अंतरावर लावा.',
  stages_en: 'Sprouting, vegetative, tuber initiation, bulking, maturity. Earthing-up helps.',
  stages_hi: 'अंकुरण, वृद्धि, कंद बनना, भराव, परिपक्वता। मिट्टी चढ़ाना लाभकारी।',
  stages_mr: 'कोंब, वाढ, कंद धरणे, पोसणे, पक्वता. भर देणे फायदेशीर.',
  irrigation_en: 'General guidance. Light frequent irrigation; stop before harvest for skin setting.',
  irrigation_hi: 'सामान्य मार्गदर्शन। हल्की बार-बार सिंचाई; खुदाई से पहले रोकें।',
  irrigation_mr: 'सर्वसाधारण मार्गदर्शन. हलके वारंवार पाणी; काढणीपूर्वी थांबवा.',
  diseases_en: 'Common: Early Blight, Late Blight. See disease details in app.',
  diseases_hi: 'सामान्य: अगेती/पछेती झुलसा। विवरण ऐप में देखें।',
  diseases_mr: 'सामान्य: अर्ली/लेट ब्लाइट. माहिती अ‍ॅपमध्ये पहा.',
  prevention_en: 'General prevention: certified seed, rotation, sanitation. No dose here - follow label.',
  prevention_hi: 'सामान्य रोकथाम: प्रमाणित बीज, चक्र, सफाई। मात्रा नहीं - लेबल मानें।',
  prevention_mr: 'सर्वसाधारण प्रतिबंध: प्रमाणित बेणे, फेरपालट, स्वच्छता. मात्रा नाही - लेबल पाळा.',
  harvest_en: 'General guidance. Harvest after haulms dry; cure tubers in shade before storage.',
  harvest_hi: 'सामान्य मार्गदर्शन। पत्ते सूखने पर खुदाई; छाया में सुखाएं।',
  harvest_mr: 'सर्वसाधारण मार्गदर्शन. पात वाळल्यावर काढणी; सावलीत वाळवा.',
  source: 'ICAR / State Agricultural University general guidance', source_url: 'https://icar.gov.in/' });
